### ISSUE TITLE
Error when uncheck use_anapnoe_ui : cagliostro-colab-ui.ipynb

### ISSUE THREAD

**Issue by tendi89** [Linaqruf/sd-notebook-collection#13]
cagliostro-colab-ui.ipynb
I encountered an error when attempting to uncheck the 'use_anapnoe_ui' option. Specifically, I received the following error message:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-1-da472018b952>](https://localhost:8080/#) in <cell line: 308>()
    306     print("All is done! Go to the next step.")
    307 
--> 308 main()

[<ipython-input-1-da472018b952>](https://localhost:8080/#) in main()
    265         extensions_list = os.listdir(extensions_dir)
    266         with tqdm(
--> 267             total=len(extensions_list) - len(skipped_extensions) - 1,
    268             desc="Updating extensions",
    269             mininterval=0,

UnboundLocalError: local variable 'skipped_extensions' referenced before assignment

![image](https://user-images.githubusercontent.com/32981387/233252888-cdf6abfa-ba92-4bb9-a881-7a966cf6a97d.png)

**Comment by Linaqruf** [comment]
I forgot to declare skipped_extensions thanks for the report, I fixed the error a while ago, 

But I removed automatic1111 version because of Google Colab ToS. And I put it back last night, you can now use Automatic1111 version instead of Anapnoe by set `repo_type` to `Automatic1111`

I'm sorry for the problem
