### ISSUE TITLE
REVERT CHANGES

### ISSUE THREAD

**Issue by Linaqruf** [Linaqruf/sd-notebook-collection#71]
I reverted both packages and the Colab notebook to the last stable version because the current one has a lot of bugs. For now, I don't have time to debug it.

Please refrain from updating the webui and extensions for the time being, thanks!

Honestly, I lost interest since Google Colab banned my notebook string. I'm going to create Comfy UI Colab with the same approach later instead.

Please understand.

**Comment by aripsam** [comment]
This is the best notebook that exists out there so thanks for your work. Looking forward to the comfy notebook.

**Comment by Lucascoolsouza** [comment]
i found a fix to still use the collab without the google warning, in this booth lines.
repo_dir= os.path.join(root_dir, "cagliostro-colab-ui")
output_drive_folder="cagliostro-colab-ui/outputs" #@param {type:'string'}
change cagliostro-colab-ui to "anyname"-ui
![Screenshot_300](https://github.com/Linaqruf/sd-notebook-collection/assets/38731510/53d32af2-7490-49d4-a01a-456e2b4d5946)

**Comment by Lucascoolsouza** [comment]
the problem just still in folder name, that is cagliostro-colab-ui, i can't rename for now

**Comment by andersenryu3** [comment]
Could anyone explain to me how to fix the disconnecting problem that I have mentioned earlier in the Issues?
And could you please fix this problem dev?

**Comment by BinaryQuantumSoul** [comment]
> Honestly, I lost interest since Google Colab banned my notebook string

Actually, it means your notebook is important enough that Google had to block it. That means people love your work

**Comment by wattzombie** [comment]
thanks : @Lucascoolsouza 

place in the first cell code :
"instal cag liostro colab"

and add :

_prefix = "cag"
suffix = "liostro-colab-ui"._

before
"# https://github.com/markdown ### Drive Config".

---------------------------------------------------copy-------------------------------------------------
``
################################
COLAB ARGUMENTS GOES HERE

################################
prefix = "cag"
suffix = "liostro-colab-ui"
https://github.com/markdown ### Drive Config

mount_drive = True # @param {type:'boolean'}
output_drive_folder = prefix + suffix #@param {type:'string'}
https://github.com/markdown ### Repo Config

repo_type = "Anapnoe" #@param ["AUTOMATIC1111", "AUTOMATIC1111-Dev", "Anapnoe"]
update_webui = False # @param {type:'boolean'}
update_extensions = False # @param {type:'boolean'}
commit_hash = "" # @param {type:'string'}
dpmpp_2m_v2_patch = True # @param {type:'boolean'}
https://github.com/markdown ### Optimization Config
https://github.com/markdown > It's not recommended to set params below to True if you have Colab Pro subscription.

colab_optimizations = True # @param {type:'boolean'}
https://github.com/markdown > Specify mobile_optimizations to keep colab tab alive for mobile users

mobile_optimizations = False # @param {type:'boolean'}

################################
DIRECTORY CONFIG

################################
VAR

voldemort, voldy = read("kq6ZmHFU")[:2]
ROOT DIR

root_dir = "/content"
drive_dir = os.path.join(root_dir, "drive", "MyDrive")
repo_dir = os.path.join(root_dir, prefix + suffix)
tmp_dir = os.path.join(root_dir, "tmp")
patches_dir = os.path.join(root_dir, "patches")
deps_dir = os.path.join(root_dir, "deps")
fused_dir = os.path.join(root_dir, "fused")
`
this is important because colab when identifying "cagliostro" at the time of loading, it starts blocking and errors are displayed.

so far this is the only thing that makes the notebook work well. let's wait for the "master" to come back.
